import { Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const lato = Lato({
  variable: "--font-lato-mono",
  subsets: ["latin"],
  weight: ["300","400","900"],
});

export const metadata = {
  title: "ShopCom | Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={lato.className}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
