    export const Hero_Data = [
  {name:"T-shirts",
  image:"https://media.istockphoto.com/id/1174118243/photo/full-length-photo-of-afro-skateboarder-with-board.jpg?s=1024x1024&w=is&k=20&c=uyZUeshoBJrxni3d8mesxgX2dIHbOUW3eU0XX9PHQxQ=",
  title:"New Brands",
  description:"everyweek new brands to make you unique",
  price:"25$"},
  {name:"T-shirts",
    image:"https://media.istockphoto.com/id/1174118243/photo/full-length-photo-of-afro-skateboarder-with-board.jpg?s=1024x1024&w=is&k=20&c=uyZUeshoBJrxni3d8mesxgX2dIHbOUW3eU0XX9PHQxQ=",
    title:"New Brands",
    description:"everyweek new brands to make you unique",
    price:"25$"},
    {name:"T-shirts",
      image:"https://media.istockphoto.com/id/1174118243/photo/full-length-photo-of-afro-skateboarder-with-board.jpg?s=1024x1024&w=is&k=20&c=uyZUeshoBJrxni3d8mesxgX2dIHbOUW3eU0XX9PHQxQ=",
      title:"New Brands",
      description:"everyweek new brands to make you unique",
      price:"25$"},
      {name:"T-shirts",
        image:"https://media.istockphoto.com/id/1174118243/photo/full-length-photo-of-afro-skateboarder-with-board.jpg?s=1024x1024&w=is&k=20&c=uyZUeshoBJrxni3d8mesxgX2dIHbOUW3eU0XX9PHQxQ=",
        title:"New Brands",
        description:"everyweek new brands to make you unique",
        price:"25$"},
  {name:"Hoodies",
  image:"https://media.istockphoto.com/id/1174118243/photo/full-length-photo-of-afro-skateboarder-with-board.jpg?s=1024x1024&w=is&k=20&c=uyZUeshoBJrxni3d8mesxgX2dIHbOUW3eU0XX9PHQxQ=",
  title:"New Styles",
  description:"A trending design and modern designs is available now",
  price:"20$"},
  {name:"Jackets",
  image:"https://media.istockphoto.com/id/1174118243/photo/full-length-photo-of-afro-skateboarder-with-board.jpg?s=1024x1024&w=is&k=20&c=uyZUeshoBJrxni3d8mesxgX2dIHbOUW3eU0XX9PHQxQ=",
  title:"New Designs",
  description:"Designs Maked carefully by more much love",
  price:"30$"}
  ]

  export const Categories_Links = ["T-shirts", "Hoodies", "Jackets"];